OrdererOrgs:
  - Name: Orderer
    Domain: testProject.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.testProject.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.testProject.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.testProject.com
    Template:
      Count: 1
    Users:
      Count: 1
